// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlcConfig

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	Email     string
}

type UsersOtp struct {
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
	ID        pgtype.UUID
	UserID    pgtype.UUID
	Otp       string
	ExpiresAt pgtype.Timestamptz
	UsedAt    pgtype.Timestamptz
}
